[libdefaults]
    default_realm = HFS.TEST
    dns_lookup_realm = true
    dns_lookup_kdc = true
    ticket_lifetime = 24h
    forwardable = true

[realms]
    HFS.TEST = {
        kdc = ipa.hfs.test:88
        admin_server = ipa.hfs.test:749
    }

[domain_realm]
    .hfs.test = HFS.TEST
    hfs.test = HFS.TEST
